#*** BEGIN - Search 2 Book Booking Engine core API ***#
booking-engine-core-services:
  base_url: http://172.23.236.41:8080/booking_engine
#*** END - Search 2 Book Booking Engine core API ***#

#*** BEGIN - URLs for Elastic Search ***#
elastic-search:
  base_url: http://172.23.236.48:5601
  booking-engine: ${elastic-search.base_url}/logstash-bookingengine*/_search
#*** END - URLs for Elastic Search ***#