batchJob:
  isEnabled: false
#*** BEGIN Configuration for Manage Booking - Reconfirmation module ***#
reconfirmation:
  batch-job-scheduling-interval: 0 0/5 * 1/1 * ? *
#*** END Configuration for Manage Booking - Reconfirmation module ***#

#*** BEGIN Configuration for TimeLimitBooking ***#
timelimit:
  batch-job-scheduling-interval: 0 0 23 1/1 * ? *
#*** END Configuration for TimeLimitBooking ***#

#*** BEGIN Configuration for SupplierBillPassingModule module ***#
stopPayment:
  batch-job-scheduling-interval: 0 0 12 1 1 ? *
supplierBillPassing:
  batch-job-scheduling-interval: 0 0/1 * 1/1 * ? *
#*** END Configuration for SupplierBillPassing module ***#

#*** BEGIN Configuration for Manage Arrival List ***#
manage-arrival-list:
  batch-job-scheduling-interval: 0 0 17 1/1 * ? *
#*** END Configuration for Manage Arrival List ***#

#***BEGIN Configuration for Manage Failure - Payment And Booking module ***#
failures:
  batch-job-scheduling-interval: 0 0/15 * 1/1 * ? *
#***END Configuration for Manage Failure - Payment And Booking module ***#

#***BEGIN Configuration for Pre Payment To Supplier Module ***#
pre-payment-to-supplier:
    batch-job-scheduling-interval: 0 30 17 1/1 * ? *
#***END Configuration for Pre Payment To Supplier Module ***#

#*** BEGIN Configuration for Manage Documentation module ***#
manageDocumentation:
  batch-job-scheduling-interval: 0 0 23 1/1 * ? *
#*** END Configuration for Manage Documentation module ***#

#***BEGIN Configuration for Manage Mailroom ***#
manage-mailroom:
  batch-job-scheduling-interval: 0 0 0 * * ?
#***END Configuration for Manage Mailroom ***#

#*** BEGIN configuration for commercial statements module ***#
commercial-statements:
  batch-job-interval: 0 0 0/3 1/1 * ? *
#*** END configuration for commercial statements module ***#

#*** BEGIN Configuration for Manage AbstractProductFactory Review module ***#
review:
  batch-job-scheduling-interval: 0 0/10 * 1/1 * ? *
#*** END Configuration for Manage product Review module ***#

#*** BEGIN Configuration for Manage Third Party Vouchers ***#
third-party-vouchers:
  batch-job-scheduling-interval: 0 1 * ? * *
#*** END Configuration for Manage Third Party Vouchers ***#

#*** BEGIN Configuration for TodoTask Reassignment Scheduled job ***#
todotask-reassignment:
  batch-job-scheduling-interval: 0 0/30 * 1/1 * ? *
#*** END Configuration for  TodoTask Reassignment Scheduled job ***#