###*** YML file to define Producers and Consumers for Operations thro Kafka ***###

#*** BEGIN Kafka Configuration ***#
kafka:
  consumer:
    bootstrap : "172.23.209.34:9092"
    BE_TOPIC: BookingEngineNotification
    MDM_PRODUCT_TOPIC: MDM.SIT.PRODUCT.PUB
    MDM_SUPPLIER_TOPIC: MDM.SIT.SUPPLIER.PUB
    BE_MESSAGE_CONSUMER_GROUP: OperationsBookingNotificationsMessageConsumerGroup5
    MDM_SUPPLIER_MESSAGE_CONSUMER_GROUP: OperationsMDMSupplierMessageConsumerGroup5
    MDM_PRODUCT_MESSAGE_CONSUMER_GROUP: OperationsMDMProductMessageConsumerGroup5
  producer:
      bootstrap: 172.23.213.29:9092
      clientId: OperationsKafkaProducer
      email:
        topic: emailTopic
        enabled: true
      supplier-commercials:
        topic: MDM.SIT.SUPPLIERCOMMERCIAL.PUB
        enabled: true
      client-commercials:
        topic: MDM.SIT.CLIENTCOMMERCIAL.PUB
        enabled: true
      booking-notifications:
        topic: bookingNotifications
        enabled: true
#*** END Kafka Configuration  ***#